
# Constants
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
SCREEN_TITLE = "Kevin: Divine Program Master"

# Constants used to scale our sprites from their original size
CHARACTER_SCALING = 1
TILE_SCALING = 0.5
SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = (SPRITE_PIXEL_SIZE * TILE_SCALING)

# Movement speed of player, in pixels per frame
PLAYER_MOVEMENT_SPEED = 5
GRAVITY = 0

# How many pixels to keep as a minimum margin between the character
# and the edge of the screen.
LEFT_VIEWPORT_MARGIN = 300
RIGHT_VIEWPORT_MARGIN = 300
BOTTOM_VIEWPORT_MARGIN = 400
TOP_VIEWPORT_MARGIN = 400

PLAYER_START_X = 64
PLAYER_START_Y = 225

# PHILLIPS_START_X = 75 * SPRITE_PIXEL_SIZE/2
# PHILLIPS_START_Y = 70 * SPRITE_PIXEL_SIZE/2

PHILLIPS_START_X = 5 * SPRITE_PIXEL_SIZE/2
PHILLIPS_START_Y = 5 * SPRITE_PIXEL_SIZE/2

TEXT_BOX_HEIGHT = 160

MUSIC_VOLUME = 0.5

